### PR TITLE
add <u></u> tag

### PR DESCRIPTION
**Pull request by EnvyIT**
Fixes https://github.com/Kotlin/kotlinx.html/issues/240

### CODE REVIEW

**Comment by jrossgatterer** [comment]
Would be great if it was supported

**Comment by florianrohrauer** [comment]
+1

**Comment by AistleitnerFabian** [comment]
+1 please review and merge 🙏

**Comment by EnvyIT** [comment]
+1 we really need this basic functionality @yole  would be great if you could give feedback that we bring this on it's way.

**Comment by eliasroebl** [comment]
+1 very much needed

**Comment by e5l** [comment]
Hey @EnvyIT, sorry for the delay! 

Thanks for the PR. LGTM.

It also would be great to have some KDocs here :)

**Pull request merged**
