### PR TITLE
Add wasmJs target support.

### PR DESCRIPTION
**Pull request by IlyaGulya**
Changes:
1. Added `wasmJs` target support
2. WasmJS target builds upon `Element` instead of `HTMLElement` because `SVGElement` does not inherit `HTMLElement` and class cast exception happens.
3. Rewritten generators using `KotlinPoet`:
  - common: `gen-consumer-tags.kt`
  - js: `gen-consumer-tags-js.kt`
  - js: `gen-event-attrs-js.kt`
  - wasmJs: `gen-consumer-tags-js.kt`
  - wasmJs: `gen-event-attrs-js.kt`
  Now `gen-consumer-tags.kt` and `gen-consumer-tags-js.kt` are generated using single generator.
4. Added tests for `js` and `wasmJs` which are checking that every generated tag is correctly instantiated in runtime.
5. Upgraded kotlin to `1.9.22`
6. Upgraded gradle to `8.5`

### CODE REVIEW

**Comment by IlyaGulya** [comment]
Sure

**Comment by IlyaGulya** [comment]
@e5l done!

**Review by e5l — APPROVED** [review]
Good job! LGTM

**Comment by IlyaGulya** [comment]
Wow, that was fast 🙂

**Pull request merged**
