### PR TITLE
Base WASM Support and metadata publishing (1.4.0-rc)

### PR DESCRIPTION
**Pull request by mpetuska**
This is essentially a #154 but from feature branch for easier management until merged
- Version bumped to 1.4.0-rc
- BOTH js compiler mode enabled
- WASM target added
- gradle metadata publishing enabled
- granular kotlin source sets enabled
- TagConsumer and dsl abstraction level raised to allow for custom event object specifications
- Native targets support

@cy6erGn0m

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Could you please resolve the conflicts?

**Comment by mpetuska** [comment]
What conflicts? Github says this branch is ready to merge

**Comment by cy6erGn0m** [comment]
General issues:
- won't compile on macos (unixMain currentTimeMillis.kt)
- formatting is wrong: 4 spaces indentation, star imports: always
- not sure why but IDEA is unable to resolve anything in native modules (something is misconfigured)

**Comment by cy6erGn0m** [comment]
Regarding parameterizing tag types with `E`: why is a particular instance of a tag parameterized with a single event type while it actually has multiple events with different types?

**Comment by mpetuska** [comment]
Hmm, odd that it won't compile on macos, it should be posix compatible and as such work through unixMain. Will try to setup hackintosh to check. 

For formatting, do you mind if i add ktlint to keep it consistent for the future?

E is meant to be used as root event class from which all other events are extended.

**Comment by mpetuska** [comment]
Resolved confilicts
Reverted formatting issues
Removed IOS/MAC targets as I couldn't test them, (however they should work via unixMain in theory, would be great for someone with mac to give it another go).
IDEA errors are due to commonizer bug(s), not being able to commonize native libs for targets unsupported by host.

Hopefully this can now be merged.

**Comment by mpetuska** [comment]
@cy6erGn0m any updates on getting this merged?

**Comment by mpetuska** [comment]
Can we please get this merged? Don't want another round of merge conflicts after it gets stale again...

**Comment by e5l** [comment]
Closed as outdated

**Pull request closed without merging**
