### PR TITLE
Self-closing empty tags to be compatible with XHTML standard.

### PR DESCRIPTION
**Pull request by atomcat1978**

### CODE REVIEW

**Comment by atomcat1978** [comment]
Maybe appendHTML could take an 
```
XHTMLOutput: Boolean = false
```
parameter. If it is set to true explicitly by the user, than we would close the tag using ```/>```.

**Comment by cy6erGn0m** [comment]
Yes, this is the best option. However I am not sure if it is the only xml compatibility issue.

**Comment by atomcat1978** [comment]
Quite a good summary on the topic: https://stackoverflow.com/questions/36175330/html-meta-tag-must-be-closed-or-not-in-xhtml

**Comment by atomcat1978** [comment]
https://github.com/Kotlin/kotlinx.html/pull/79/commits/71ec05005477ad036749fc3354bb1ed05cf3ed81

**Comment by cy6erGn0m** [comment]
Thanks!

**Comment by atomcat1978** [comment]
U R welcome:)

**Pull request merged**
