### PR TITLE
Added integrity attributes for script and link tags

### PR DESCRIPTION
**Pull request by jonare**
Subresource integrity allows developers to load external resources in a secure manner https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

### CODE REVIEW

**Comment by jonare** [comment]
We'd also like to ask for a release after merge, to allow us to use this feature and the CSP nonce attribute from the previous PR from an official version. Thanks!

**Comment by jonare** [comment]
@cy6erGn0m I see the tests failed after merging. Did I miss anything? https://teamcity.jetbrains.com/viewLog.html?buildId=1780343&buildTypeId=KotlinTools_KotlinxHtml_Build

**Comment by jonare** [comment]
Hey, @cy6erGn0m. Do you have any estimates for when the next release might be?

**Comment by cy6erGn0m** [comment]
0.6.12

**Comment by jonare** [comment]
Thanks!

**Pull request merged**
