### PR TITLE
Enable building of jvm classes using the simple Kobalt syntax

### PR DESCRIPTION
**Pull request by pabl0rg**
These few changes make it possible to compile and assemble (make jars) of kotlinx.html so that the jvm stuff can at least be built and used (maven build seems to be broken).

If you'd like to use Kobalt, I can add the config for publishing jars to Sonatype, etc.  It will also be simple.

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
What is the idea to build it with kobalt? Why do you build it at your side?

**Comment by pabl0rg** [comment]
Hi

I want to try applying the same concept to KML.  Also, i couldn't find the
right jar for kotlinx.html and the maven build fails.

**Comment by cy6erGn0m** [comment]
@pabl0rg hm, the build is green now (there was a temporary problem at build server so it was red)

**Comment by cy6erGn0m** [comment]
Perhaps the documentation need to be updated to make artefacts purpose clear

**Comment by pabl0rg** [comment]
That would be helpful.  One thing that might be worth clarifying is if
there's any relation to the kotlinx.html in the kara framework (the code
there looks pretty different -- it's not generated from
xsd).  Does JetBrains plans to eventually use it in tge Kara Framework or
maybe replace Kara with something else?

Have you ever heard of the Rythm template engine?

It has some cool features that I was going to see if I could add to
kotlinx.html:
- hot page compilation & reloading (independent of IDE)
- i18n (how should one do this in kotlinx.html?)

I have decided to wait before starting on this b/c
kotlinc-embeddable-compiler.jar would be a huge dependency (20MB).  I found
an undocumented daemon mode for kotlinc that might solve the problem but am
not sure if we are encouraged to use it or how best to do so.  Also I am
not a kotlin expert yet.

**Comment by cy6erGn0m** [comment]
Hot page compilation & reloading

There are three approaches: 
- during debug session you could try to hotswap classes (not always work because of JVM limitations on schema change)
- custom classloader with embedded kotlinc (potentially better but kotlinc is quite big and hasn't yet stable API
- syntax tree serialization (Kotlin feature, planned but unscheduled yet) so it could be evaluated in runtime 

Unfortunately for now the only option 1 works for now, the second one is possible to implement while the third one is impossible for now

regarding i18: you can do it any way simply via kotlin functions: i see no reason to have such a difficult mechanism as it was done in Rythm engine

**Pull request closed without merging**
